
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: all-issue-comments-display
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display

---

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: all-issue-comments
spec:
  broker: github-events
  filter:
    attributes:
      type: dev.knative.source.github.issue_comment
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: all-issue-comments-display
